server:
  port: 14000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - name: CircuitBreaker
          args:
            name: backendA
            fallbackUri: forward:/fallback
      routes:
        - id: userServer
          uri: lb://user-server
          predicates:
            - Path=/user/**
        - id: foodServer
          uri: lb://food-server
          predicates:
            - Path=/food/**
        - id: businessServer
          uri: lb://business-server
          predicates:
            - Path=/business/**
        - id: cartServer
          uri: lb://cart-server
          predicates:
            - Path=/cart/**
        - id: deliveryAddressServer
          uri: lb://deliveryAddress-server
          predicates:
            - Path=/deliveryAddress/**
        - id: ordersServer
          uri: lb://orders-server
          predicates:
            - Path=/orders/**
        - id: fileServer
          uri: lb://file-server
          predicates:
            - Path=/file/**

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13002:13002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - config-server

logging:
  level:
    org:
      springframework:
        security: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 30
        minimum-number-of-calls: 1
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 2s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      backendA:
        base-config: default